


# 数据库
spring:
  datasource:
    url: jdbc:mysql://39.105.113.51:3306/dousheng?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ZZQ0902zzq
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 39.105.113.51
    port: 6379
    password: ZZQ0902zzq
