# 端口
server:
  port: 9999

# 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dousheng?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  # 驼峰转换为下划线
  jackson:
    property-naming-strategy: SNAKE_CASE

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzqedu.dousheng.dao.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-level: TRACE

# openapi
springdoc:
  api-docs:
    enabled: true





