name: lane build and upload

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@master
        with:
          java-version: 8
          distribution: "adopt"
          cache: maven
      - run: mvn clean -DfinalName=dousheng package --file pom.xml
      - name: copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "target/lane-formal.jar"
          rm: true
          target: "/www/test"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 20s
          script: |
            cd /www/test
            ps -ef | grep dousheng.jar | grep -v grep | awk '{print $2}' | xargs kill -9 
            nohup java -jar dousheng.jar --spring.profiles.active=pro > nohup.out &
            pwd
            exit